settings:
  react:
    version: detect
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react-hooks/recommended
overrides:
  - files:
      - src/**/*.test.ts
      - src/**/*.test.tsx
    env:
      jest: true
    extends:
      - plugin:jest/recommended
    plugins:
      - jest
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  tsconfigRootDir: __dirname,
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - '@typescript-eslint'
rules:
  prettier/prettier: error
ignorePatterns:
  - cypress/**/*
